# Memory / ZRAM behavior (Bazzite-style)
vm.swappiness = 180
vm.vfs_cache_pressure = 300
vm.dirty_background_ratio = 2
vm.dirty_ratio = 40
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0

# Gaming stability (winterofhell from github)
vm.max_map_count = 16777216